-- Placeholder event type for dynamic zombie hordes.
-- Will be implemented in a future version.
--
-- Intended behavior:
--   Spawn a large group of zombies at a point and have them move directionally
--   across the map, like DayZ hordes. May use IsoWorld:CreateSwarm() or
--   custom pathfinding.

-- DE.EventManager.register({
--     id             = "horde",
--     name           = "Zombie Horde",
--     weight         = 5,
--     cooldownHours  = 96,
--     minDaysSurvived = 7,
--     locations = {},
--     spawn = function(x, y, z) end,
-- })
